
version: '3.8'
services:
   tattoo_marketplace_db:
     image: postgres
     container_name: tattoo_marketplace_db
     environment:
       - POSTGRES_USER=postgres
       - POSTGRES_PASSWORD=postgres
       - POSTGRES_DB=tattoo_marketplace
     ports:
       - "5432:5432"
     networks:
       - tattoo_network
  
   app:
     build:
       context: .
     container_name: app
     depends_on:
       - tattoo_marketplace_db
     environment:
       - SPRING_DATASOURCE_URL=jdbc:postgresql://tattoo_marketplace_db:5432/tattoo_marketplace
       - SPRING_DATASOURCE_USERNAME=postgres
       - SPRING_DATASOURCE_PASSWORD=postgres
       - SPRING_JPA_HIBERNATE_DDL_AUTO=update
     ports:
       - "8089:8089"
     networks:
       - tattoo_network

   maven:
     image: maven:3.8.5-openjdk-17
     volumes:
       - .:/app 
       - ~/.m2:/root/.m2  
     working_dir: /app
     networks:
       - tattoo_network

networks:
  tattoo_network:
    driver: bridge
